import type { Topic, Question, Flashcard, ExamConfig } from '@/types'
import { addDays, format } from 'date-fns'

export const demoTopics: Topic[] = [
  { id: 'demo-1', title: 'Algebra Basics', category: 'Mathematics', difficulty: 2, importance: 4 },
  { id: 'demo-2', title: 'Quadratic Equations', category: 'Mathematics', difficulty: 3, importance: 5 },
  { id: 'demo-3', title: 'Trigonometry', category: 'Mathematics', difficulty: 4, importance: 4 },
  { id: 'demo-4', title: 'Calculus: Derivatives', category: 'Mathematics', difficulty: 5, importance: 5 },
  { id: 'demo-5', title: 'World War I', category: 'History', difficulty: 3, importance: 4 },
  { id: 'demo-6', title: 'World War II', category: 'History', difficulty: 3, importance: 5 },
  { id: 'demo-7', title: 'Cold War', category: 'History', difficulty: 4, importance: 4 },
  { id: 'demo-8', title: 'Cell Structure', category: 'Biology', difficulty: 2, importance: 3 },
  { id: 'demo-9', title: 'Photosynthesis', category: 'Biology', difficulty: 3, importance: 4 },
  { id: 'demo-10', title: 'Genetics', category: 'Biology', difficulty: 4, importance: 5 },
  { id: 'demo-11', title: 'Shakespeare', category: 'Literature', difficulty: 3, importance: 4 },
  { id: 'demo-12', title: 'Poetry Analysis', category: 'Literature', difficulty: 4, importance: 3 },
  { id: 'demo-13', title: 'Chemical Bonds', category: 'Chemistry', difficulty: 3, importance: 4 },
  { id: 'demo-14', title: 'Organic Chemistry', category: 'Chemistry', difficulty: 5, importance: 5 },
  { id: 'demo-15', title: 'Newton\'s Laws', category: 'Physics', difficulty: 3, importance: 4 },
]

export const demoQuestions: Question[] = [
  // Algebra
  {
    id: 'q-1',
    topicId: 'demo-1',
    prompt: 'What is the value of x in 2x + 5 = 15?',
    choices: ['x = 3', 'x = 5', 'x = 7', 'x = 10'],
    answerIndex: 1,
    explanation: 'Subtract 5 from both sides: 2x = 10, then divide by 2: x = 5',
  },
  {
    id: 'q-2',
    topicId: 'demo-1',
    prompt: 'Simplify: 3(x + 2) - 2x',
    choices: ['x + 6', 'x + 2', '5x + 6', 'x - 6'],
    answerIndex: 0,
    explanation: 'Distribute: 3x + 6 - 2x = x + 6',
  },
  {
    id: 'q-3',
    topicId: 'demo-1',
    prompt: 'Solve for y: 4y - 8 = 12',
    choices: ['y = 1', 'y = 5', 'y = 4', 'y = 20'],
    answerIndex: 1,
    explanation: 'Add 8: 4y = 20, divide by 4: y = 5',
  },
  // Quadratic Equations
  {
    id: 'q-4',
    topicId: 'demo-2',
    prompt: 'What are the solutions to x² - 5x + 6 = 0?',
    choices: ['x = 2, x = 3', 'x = 1, x = 6', 'x = -2, x = -3', 'x = 0, x = 5'],
    answerIndex: 0,
    explanation: 'Factor: (x - 2)(x - 3) = 0, so x = 2 or x = 3',
  },
  {
    id: 'q-5',
    topicId: 'demo-2',
    prompt: 'What is the discriminant of x² + 4x + 4 = 0?',
    choices: ['0', '4', '8', '16'],
    answerIndex: 0,
    explanation: 'Discriminant = b² - 4ac = 16 - 16 = 0',
  },
  {
    id: 'q-6',
    topicId: 'demo-2',
    prompt: 'Complete the square: x² + 6x + ?',
    choices: ['+9', '+12', '+18', '+36'],
    answerIndex: 0,
    explanation: 'Half of 6 is 3, square it: 3² = 9',
  },
  // Trigonometry
  {
    id: 'q-7',
    topicId: 'demo-3',
    prompt: 'What is sin(30°)?',
    choices: ['0', '0.5', '√3/2', '1'],
    answerIndex: 1,
    explanation: 'sin(30°) = 1/2 = 0.5',
  },
  {
    id: 'q-8',
    topicId: 'demo-3',
    prompt: 'What is cos(60°)?',
    choices: ['0', '0.5', '√3/2', '1'],
    answerIndex: 1,
    explanation: 'cos(60°) = 1/2 = 0.5',
  },
  {
    id: 'q-9',
    topicId: 'demo-3',
    prompt: 'In a right triangle, if opposite = 3 and hypotenuse = 5, what is sin(θ)?',
    choices: ['3/5', '4/5', '3/4', '5/3'],
    answerIndex: 0,
    explanation: 'sin(θ) = opposite/hypotenuse = 3/5',
  },
  // Calculus
  {
    id: 'q-10',
    topicId: 'demo-4',
    prompt: 'What is the derivative of x²?',
    choices: ['x', '2x', 'x²', '2x²'],
    answerIndex: 1,
    explanation: 'd/dx(x²) = 2x using power rule',
  },
  {
    id: 'q-11',
    topicId: 'demo-4',
    prompt: 'What is the derivative of sin(x)?',
    choices: ['cos(x)', '-cos(x)', 'sin(x)', '-sin(x)'],
    answerIndex: 0,
    explanation: 'd/dx(sin(x)) = cos(x)',
  },
  {
    id: 'q-12',
    topicId: 'demo-4',
    prompt: 'What is the derivative of e^x?',
    choices: ['e^x', 'xe^x', 'e^(x-1)', 'ln(x)'],
    answerIndex: 0,
    explanation: 'd/dx(e^x) = e^x',
  },
  // World War I
  {
    id: 'q-13',
    topicId: 'demo-5',
    prompt: 'When did World War I begin?',
    choices: ['1914', '1915', '1916', '1917'],
    answerIndex: 0,
    explanation: 'World War I began in 1914',
  },
  {
    id: 'q-14',
    topicId: 'demo-5',
    prompt: 'What event triggered the start of WWI?',
    choices: [
      'Assassination of Archduke Franz Ferdinand',
      'Invasion of Belgium',
      'Sinking of Lusitania',
      'Russian Revolution',
    ],
    answerIndex: 0,
    explanation: 'The assassination of Archduke Franz Ferdinand in Sarajevo triggered the war',
  },
  {
    id: 'q-15',
    topicId: 'demo-5',
    prompt: 'Which countries formed the Triple Entente?',
    choices: [
      'France, Russia, UK',
      'Germany, Austria-Hungary, Italy',
      'USA, UK, France',
      'Russia, Germany, Austria',
    ],
    answerIndex: 0,
    explanation: 'Triple Entente: France, Russia, and United Kingdom',
  },
  // World War II
  {
    id: 'q-16',
    topicId: 'demo-6',
    prompt: 'When did World War II end?',
    choices: ['1944', '1945', '1946', '1947'],
    answerIndex: 1,
    explanation: 'WWII ended in 1945',
  },
  {
    id: 'q-17',
    topicId: 'demo-6',
    prompt: 'Which battle was the turning point in the Pacific?',
    choices: ['Pearl Harbor', 'Midway', 'Iwo Jima', 'Okinawa'],
    answerIndex: 1,
    explanation: 'Battle of Midway (1942) was the turning point',
  },
  {
    id: 'q-18',
    topicId: 'demo-6',
    prompt: 'Operation Barbarossa was the invasion of:',
    choices: ['France', 'Poland', 'Soviet Union', 'North Africa'],
    answerIndex: 2,
    explanation: 'Operation Barbarossa was Germany\'s invasion of the Soviet Union',
  },
  // Cold War
  {
    id: 'q-19',
    topicId: 'demo-7',
    prompt: 'The Berlin Wall was built in:',
    choices: ['1945', '1955', '1961', '1971'],
    answerIndex: 2,
    explanation: 'Berlin Wall was built in 1961',
  },
  {
    id: 'q-20',
    topicId: 'demo-7',
    prompt: 'Which doctrine aimed to contain communism?',
    choices: ['Monroe Doctrine', 'Truman Doctrine', 'Marshall Plan', 'NATO'],
    answerIndex: 1,
    explanation: 'Truman Doctrine (1947) aimed to contain Soviet expansion',
  },
  // Cell Structure
  {
    id: 'q-21',
    topicId: 'demo-8',
    prompt: 'What is the powerhouse of the cell?',
    choices: ['Nucleus', 'Mitochondria', 'Ribosome', 'Golgi apparatus'],
    answerIndex: 1,
    explanation: 'Mitochondria produce ATP, the cell\'s energy currency',
  },
  {
    id: 'q-22',
    topicId: 'demo-8',
    prompt: 'Which organelle contains DNA?',
    choices: ['Mitochondria', 'Ribosome', 'Nucleus', 'Endoplasmic Reticulum'],
    answerIndex: 2,
    explanation: 'Nucleus contains the cell\'s DNA',
  },
  {
    id: 'q-23',
    topicId: 'demo-8',
    prompt: 'What is the function of ribosomes?',
    choices: [
      'Energy production',
      'Protein synthesis',
      'DNA storage',
      'Waste removal',
    ],
    answerIndex: 1,
    explanation: 'Ribosomes synthesize proteins',
  },
  // Photosynthesis
  {
    id: 'q-24',
    topicId: 'demo-9',
    prompt: 'What gas do plants absorb during photosynthesis?',
    choices: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
    answerIndex: 2,
    explanation: 'Plants absorb CO₂ during photosynthesis',
  },
  {
    id: 'q-25',
    topicId: 'demo-9',
    prompt: 'Where does photosynthesis occur?',
    choices: ['Mitochondria', 'Nucleus', 'Chloroplasts', 'Ribosomes'],
    answerIndex: 2,
    explanation: 'Photosynthesis occurs in chloroplasts',
  },
  {
    id: 'q-26',
    topicId: 'demo-9',
    prompt: 'What is the main product of photosynthesis?',
    choices: ['ATP', 'Glucose', 'Oxygen', 'Water'],
    answerIndex: 1,
    explanation: 'Glucose (C₆H₁₂O₆) is the main product',
  },
  // Genetics
  {
    id: 'q-27',
    topicId: 'demo-10',
    prompt: 'How many chromosomes do humans have?',
    choices: ['23', '46', '64', '92'],
    answerIndex: 1,
    explanation: 'Humans have 46 chromosomes (23 pairs)',
  },
  {
    id: 'q-28',
    topicId: 'demo-10',
    prompt: 'What does DNA stand for?',
    choices: [
      'Deoxyribonucleic Acid',
      'Ribonucleic Acid',
      'Deoxyribose Nucleic',
      'Double Nucleic Acid',
    ],
    answerIndex: 0,
    explanation: 'DNA = Deoxyribonucleic Acid',
  },
  {
    id: 'q-29',
    topicId: 'demo-10',
    prompt: 'What is a dominant allele?',
    choices: [
      'An allele that is always expressed',
      'An allele that is never expressed',
      'An allele that masks recessive traits',
      'An allele that causes disease',
    ],
    answerIndex: 2,
    explanation: 'Dominant alleles mask recessive alleles when present',
  },
  // Shakespeare
  {
    id: 'q-30',
    topicId: 'demo-11',
    prompt: 'Who wrote "Romeo and Juliet"?',
    choices: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
    answerIndex: 1,
    explanation: 'William Shakespeare wrote Romeo and Juliet',
  },
  {
    id: 'q-31',
    topicId: 'demo-11',
    prompt: 'In which play does "To be or not to be" appear?',
    choices: ['Macbeth', 'Hamlet', 'Othello', 'King Lear'],
    answerIndex: 1,
    explanation: '"To be or not to be" is from Hamlet',
  },
  {
    id: 'q-32',
    topicId: 'demo-11',
    prompt: 'What type of play is "A Midsummer Night\'s Dream"?',
    choices: ['Tragedy', 'History', 'Comedy', 'Sonnet'],
    answerIndex: 2,
    explanation: 'A Midsummer Night\'s Dream is a comedy',
  },
  // Poetry
  {
    id: 'q-33',
    topicId: 'demo-12',
    prompt: 'What is a sonnet?',
    choices: [
      'A 14-line poem',
      'A 10-line poem',
      'A free verse poem',
      'A narrative poem',
    ],
    answerIndex: 0,
    explanation: 'A sonnet is a 14-line poem with a specific rhyme scheme',
  },
  {
    id: 'q-34',
    topicId: 'demo-12',
    prompt: 'What is iambic pentameter?',
    choices: [
      '5 stressed syllables per line',
      '10 syllables per line, alternating stress',
      'Free verse',
      'Rhyming couplets',
    ],
    answerIndex: 1,
    explanation: 'Iambic pentameter: 10 syllables with alternating unstressed/stressed pattern',
  },
  // Chemical Bonds
  {
    id: 'q-35',
    topicId: 'demo-13',
    prompt: 'What type of bond shares electrons?',
    choices: ['Ionic', 'Covalent', 'Hydrogen', 'Metallic'],
    answerIndex: 1,
    explanation: 'Covalent bonds share electrons between atoms',
  },
  {
    id: 'q-36',
    topicId: 'demo-13',
    prompt: 'What is the octet rule?',
    choices: [
      'Atoms want 8 valence electrons',
      'Atoms want 8 total electrons',
      'Molecules have 8 atoms',
      'Bonds form in groups of 8',
    ],
    answerIndex: 0,
    explanation: 'Octet rule: atoms tend to gain/lose/share electrons to have 8 valence electrons',
  },
  {
    id: 'q-37',
    topicId: 'demo-13',
    prompt: 'What is the charge of an ion with 11 protons and 10 electrons?',
    choices: ['+1', '-1', '0', '+2'],
    answerIndex: 0,
    explanation: '11 protons - 10 electrons = +1 charge',
  },
  // Organic Chemistry
  {
    id: 'q-38',
    topicId: 'demo-14',
    prompt: 'What is the general formula for alkanes?',
    choices: ['CnH2n', 'CnH2n+2', 'CnH2n-2', 'CnHn'],
    answerIndex: 1,
    explanation: 'Alkanes: CnH2n+2 (saturated hydrocarbons)',
  },
  {
    id: 'q-39',
    topicId: 'demo-14',
    prompt: 'How many carbons are in methane?',
    choices: ['1', '2', '3', '4'],
    answerIndex: 0,
    explanation: 'Methane (CH₄) has 1 carbon atom',
  },
  {
    id: 'q-40',
    topicId: 'demo-14',
    prompt: 'What functional group is -OH?',
    choices: ['Aldehyde', 'Ketone', 'Alcohol', 'Carboxylic Acid'],
    answerIndex: 2,
    explanation: '-OH is the hydroxyl group, characteristic of alcohols',
  },
  // Newton's Laws
  {
    id: 'q-41',
    topicId: 'demo-15',
    prompt: 'Newton\'s First Law is also called:',
    choices: [
      'Law of Acceleration',
      'Law of Inertia',
      'Law of Action-Reaction',
      'Law of Gravity',
    ],
    answerIndex: 1,
    explanation: 'First Law: Law of Inertia - objects at rest stay at rest',
  },
  {
    id: 'q-42',
    topicId: 'demo-15',
    prompt: 'F = ma represents which law?',
    choices: ['First Law', 'Second Law', 'Third Law', 'Law of Gravity'],
    answerIndex: 1,
    explanation: 'F = ma is Newton\'s Second Law',
  },
  {
    id: 'q-43',
    topicId: 'demo-15',
    prompt: 'What is Newton\'s Third Law?',
    choices: [
      'F = ma',
      'For every action, there is an equal and opposite reaction',
      'Objects at rest stay at rest',
      'Gravity is proportional to mass',
    ],
    answerIndex: 1,
    explanation: 'Third Law: Action-reaction pairs',
  },
]

export const demoFlashcards: Flashcard[] = [
  {
    id: 'fc-1',
    topicId: 'demo-1',
    front: 'What is the order of operations?',
    back: 'PEMDAS: Parentheses, Exponents, Multiplication/Division, Addition/Subtraction',
    streak: 0,
  },
  {
    id: 'fc-2',
    topicId: 'demo-2',
    front: 'Quadratic formula',
    back: 'x = (-b ± √(b² - 4ac)) / 2a',
    streak: 0,
  },
  {
    id: 'fc-3',
    topicId: 'demo-3',
    front: 'sin²θ + cos²θ = ?',
    back: '1 (Pythagorean identity)',
    streak: 0,
  },
  {
    id: 'fc-4',
    topicId: 'demo-5',
    front: 'Triple Alliance members',
    back: 'Germany, Austria-Hungary, Italy',
    streak: 0,
  },
  {
    id: 'fc-5',
    topicId: 'demo-8',
    front: 'Function of mitochondria',
    back: 'Produce ATP through cellular respiration',
    streak: 0,
  },
  {
    id: 'fc-6',
    topicId: 'demo-9',
    front: 'Photosynthesis equation',
    back: '6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂',
    streak: 0,
  },
]

export function getDemoExamConfig(): ExamConfig {
  return {
    examDate: format(addDays(new Date(), 30), 'yyyy-MM-dd'),
    minutesPerDay: 120,
    daysOfWeek: [1, 2, 3, 4, 5], // Monday-Friday
    startDate: format(new Date(), 'yyyy-MM-dd'),
  }
}
